# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Stat.create([
  { :name => "Pythagorean Win Expectaion", :description => "", :created_at => "2013-01-15 04:55:49", :updated_at => "2013-01-15 04:55:49", :slug => "pyth", :order => "descending", :abbreviation => "Pyth" },
  { :name => "Adjusted Defensive Efficiency", :description => "", :created_at => "2013-01-15 04:56:01", :updated_at => "2013-01-15 04:56:01", :slug => "adjusted_defensive_efficiency", :order => "ascending", :abbreviation => "Adj. Def. Eff." },
  { :name => "Defensive Clear Rate", :description => "", :created_at => "2013-01-15 04:56:17", :updated_at => "2013-01-15 04:56:17", :slug => "defensive_clear_rate", :order => "ascending", :abbreviation => "Def Clear %" },
  { :name => "Face Off Win Rate", :description => "", :created_at => "2013-01-15 04:56:34", :updated_at => "2013-01-15 04:56:34", :slug => "faceoff_percentage", :order => "descending", :abbreviation => "FO%" },
  { :name => "Offensive Clear Percentage", :description => "", :created_at => "2013-01-15 04:56:51", :updated_at => "2013-01-15 04:56:51", :slug => "offensive_clear_rate", :order => "descending", :abbreviation => "Off Clear %" },
  { :name => "Pace", :description => "", :created_at => "2013-01-15 04:57:15", :updated_at => "2013-01-15 04:57:15", :slug => "pace", :order => "descending", :abbreviation => "Pace" },
  { :name => "Adjusted Offensive Efficiency", :description => "", :created_at => "2013-01-15 04:57:36", :updated_at => "2013-01-15 04:57:36", :slug => "adjusted_offensive_efficiency", :order => "descending", :abbreviation => "Adj. Off. Eff." },
  { :name => "Possession Percentage", :description => "", :created_at => "2013-01-15 05:00:07", :updated_at => "2013-01-15 05:00:07", :slug => "pos_percentage", :order => "descending", :abbreviation => "Pos %" },
  { :name => "Strength of Schedule", :description => "Opponent pythagorean win percentages", :created_at => "2013-01-21 17:52:34", :updated_at => "2013-01-21 17:58:15", :slug => "opp_pyth", :order => "descending", :abbreviation => "S.O.S." }
], :without_protection => true )


